import { describe, it, expect } from 'vitest';
import { buildDigest, digestSession, promptsSince, MAX_PROMPTS, type DigestInput } from '../../src/core/digest.js';
import type { TranscriptEntry } from '../../src/core/transcript-entry.js';

const T0 = Date.parse('2026-09-29T08:00:00Z');
const at = (min: number) => new Date(T0 + min * 60_000).toISOString();
const you = (min: number, content: unknown, extra: Partial<TranscriptEntry> = {}): TranscriptEntry =>
  ({ type: 'user', timestamp: at(min), message: { content }, ...extra });

describe('promptsSince', () => {
  it('keeps what you typed in the window, oldest first, once', () => {
    const t: TranscriptEntry[] = [
      you(-30, 'yesterday: set up the repo'),
      you(5, 'Add the CSV export'),
      { type: 'assistant', timestamp: at(6), message: { content: 'On it' } },
      you(7, [{ type: 'tool_result', tool_use_id: 'x', content: 'ok' }]), // Claude's own loop
      you(8, '<command-name>/clear</command-name>'),
      you(9, 'Caveat: The messages below were generated by the user while running local commands.'),
      you(10, 'meta', { isMeta: true }),
      you(11, 'subagent prompt', { isSidechain: true }),
      you(12, [{ type: 'text', text: 'Also   quote\ncommas' }]),
      you(13, 'Add the CSV export'), // repeated
    ];
    expect(promptsSince([t], T0)).toEqual([
      { ts: at(5), text: 'Add the CSV export' },
      { ts: at(12), text: 'Also quote commas' },
    ]);
  });

  it('merges several conversations by time and clips long prompts', () => {
    const a = [you(20, 'second')];
    const b = [you(10, 'first'), you(30, 'x'.repeat(500))];
    const p = promptsSince([a, b], T0);
    expect(p.map((x) => x.text.slice(0, 6))).toEqual(['first', 'second', 'xxxxxx']);
    expect(p[2].text).toHaveLength(240);
  });
});

const input = (over: Partial<DigestInput> = {}): DigestInput => ({
  sessionId: 's1', target: 'api', branch: 'feat/x', isGroup: false,
  lastAccessedAt: at(0), archivedAt: null, status: null, transcripts: [], checkpoints: [], diffStat: null, ci: null,
  ...over,
});

describe('digestSession', () => {
  it('counts the turns finished in the window, with the names already made', () => {
    const d = digestSession(
      input({
        checkpoints: [
          { id: 0, ts: at(1), label: 'Initial' },
          { id: 1, ts: at(-60), label: 'yesterday' },
          { id: 2, ts: at(20), label: 'Wrote the export' },
          { id: 3, ts: at(40) },
        ],
        status: { state: 'idle', summary: 'Done: export + tests', updatedAt: at(41) },
      }),
      T0,
    )!;
    expect(d.turns).toBe(2);
    expect(d.turnLabels).toEqual(['Wrote the export']);
    expect(d).toMatchObject({ state: 'idle', summary: 'Done: export + tests', lastActivity: at(41) });
  });

  it('is left out when nothing happened in the window', () => {
    expect(digestSession(input({ transcripts: [[you(-5, 'old')]], checkpoints: [{ id: 1, ts: at(-5) }] }), T0)).toBeNull();
  });

  it('a PR merged in the window counts, even without prompts; lists every PR', () => {
    const ci = {
      checkedAt: at(50),
      repos: [
        { name: 'api', done: true, pr: { number: 7, url: 'u7', state: 'MERGED' as const, mergedAt: at(45), isDraft: false, mergeStateStatus: 'CLEAN', checks: 'pass' as const, headSha: 'a' } },
        { name: 'web', done: false, pr: null },
      ],
    };
    const d = digestSession(input({ ci }), T0)!;
    expect(d.prs).toEqual([{ repo: 'api', number: 7, url: 'u7', state: 'MERGED', mergedAt: at(45) }]);
  });

  it(`keeps the last ${MAX_PROMPTS} prompts and says how many came before`, () => {
    const t = Array.from({ length: MAX_PROMPTS + 3 }, (_, i) => you(i + 1, `prompt ${i}`));
    const d = digestSession(input({ transcripts: [t] }), T0)!;
    expect(d.prompts).toHaveLength(MAX_PROMPTS);
    expect(d.prompts[0].text).toBe('prompt 3');
    expect(d.morePrompts).toBe(3);
  });
});

describe('buildDigest', () => {
  it('only sessions that did something, most recent first', () => {
    const rows = buildDigest(
      [
        input({ sessionId: 'early', transcripts: [[you(5, 'a')]] }),
        input({ sessionId: 'quiet' }),
        input({ sessionId: 'late', transcripts: [[you(50, 'b')]] }),
        input({ sessionId: 'archived', archivedAt: at(30) }),
      ],
      T0,
    );
    expect(rows.map((r) => r.sessionId)).toEqual(['late', 'archived', 'early']);
  });
});
