import fs from 'node:fs';
import path from 'node:path';
import { defaultRunner, type CommandRunner } from '../pr/ship.js';

/**
 * Build output inside worktrees: node_modules, bin/obj, .next, target, … —
 * most of a worktree's disk, and all of it regenerated by the next install
 * or build. Clearing it in sessions you haven't used for a while gives the
 * space back without archiving them.
 *
 * Safety: a folder is only ever counted or deleted when git IGNORES it
 * (`git check-ignore`: tracked content is never reported as ignored), and
 * the check runs again right before deleting. Symlinks and junctions (pnpm)
 * are neither followed nor sized; deleting removes the link, not its target.
 * A nested repository or worktree (a folder with its own `.git`, such as
 * `.claude/worktrees/<agent>`) is never entered: the outer repo's
 * check-ignore calls its node_modules ignored, but that tree is someone
 * else's, maybe in use right now.
 */

export const BUILD_DIR_NAMES = new Set([
  'node_modules',
  'bin',
  'obj',
  'dist',
  'build',
  'out',
  'target',
  'coverage',
  '.next',
  '.nuxt',
  '.turbo',
  '.vite',
  '.angular',
  '.parcel-cache',
  '.svelte-kit',
  '.gradle',
  '.pytest_cache',
  '__pycache__',
]);
const SKIP = new Set(['.git']);

/** A relative path inside build output or `.git` (any folder of it named as one): never copied around. */
export function isBuildOutputPath(rel: string): boolean {
  return rel.split(/[\\/]/).some((seg) => SKIP.has(seg) || BUILD_DIR_NAMES.has(seg));
}

/** Folders under `root` whose name is a build-output name (not descending into them, nor into nested repos). */
export async function candidateBuildDirs(root: string, maxDepth = 4): Promise<string[]> {
  const found: string[] = [];
  const walk = async (dir: string, depth: number): Promise<void> => {
    let entries: fs.Dirent[];
    try {
      entries = await fs.promises.readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }
    if (depth > 0 && entries.some((e) => e.name === '.git')) return; // another repo or worktree
    for (const e of entries) {
      if (!e.isDirectory() || SKIP.has(e.name)) continue; // a symlink/junction is not a Dirent directory
      const full = path.join(dir, e.name);
      if (BUILD_DIR_NAMES.has(e.name)) found.push(full);
      else if (depth < maxDepth) await walk(full, depth + 1);
    }
  };
  await walk(root, 0);
  return found;
}

/** Of `dirs` (inside the repo at `root`), the ones git ignores. */
export async function ignoredByGit(root: string, dirs: string[], run: CommandRunner = defaultRunner): Promise<Set<string>> {
  if (dirs.length === 0) return new Set();
  const rel = dirs.map((d) => path.relative(root, d).replace(/\\/g, '/'));
  // Exit 0: some ignored (listed); 1: none; anything else: we can't tell — nothing counts.
  const r = await run('git', ['-C', root, 'check-ignore', '--', ...rel], root);
  if (r.code !== 0) return new Set();
  const ignored = new Set(
    r.stdout
      .split(/\r?\n/)
      .map((l) => l.trim())
      .filter(Boolean),
  );
  return new Set(dirs.filter((_, i) => ignored.has(rel[i])));
}

/** Bytes in a folder (not following links), without blocking the event loop. */
export async function folderBytes(dir: string): Promise<number> {
  let total = 0;
  const stack = [dir];
  while (stack.length) {
    const d = stack.pop()!;
    let entries: fs.Dirent[];
    try {
      entries = await fs.promises.readdir(d, { withFileTypes: true });
    } catch {
      continue;
    }
    await Promise.all(
      entries.map(async (e) => {
        const full = path.join(d, e.name);
        if (e.isDirectory()) stack.push(full);
        else if (e.isFile()) {
          try {
            total += (await fs.promises.lstat(full)).size;
          } catch {
            /* vanished */
          }
        }
      }),
    );
  }
  return total;
}

export type { BuildFolder } from '../api-types.js';
import type { BuildFolder } from '../api-types.js';

/** A worktree's ignored build folders, sized. */
export async function buildFoldersOf(root: string, run?: CommandRunner): Promise<BuildFolder[]> {
  const dirs = await ignoredByGit(root, await candidateBuildDirs(root), run);
  const out: BuildFolder[] = [];
  for (const d of dirs) out.push({ path: d, bytes: await folderBytes(d) });
  return out.sort((a, b) => b.bytes - a.bytes);
}

/**
 * Delete a worktree's build folders: the ones git ignores RIGHT NOW (checked
 * again here), never anything tracked. Returns what went.
 */
export async function clearBuildFolders(
  root: string,
  run?: CommandRunner,
): Promise<{ removed: string[]; failed: Array<{ path: string; error: string }> }> {
  const dirs = await ignoredByGit(root, await candidateBuildDirs(root), run);
  const removed: string[] = [];
  const failed: Array<{ path: string; error: string }> = [];
  for (const d of dirs) {
    try {
      await fs.promises.rm(d, { recursive: true, force: true, maxRetries: 3, retryDelay: 200 });
      removed.push(d);
    } catch (err) {
      failed.push({ path: d, error: (err as Error).message });
    }
  }
  return { removed, failed };
}
