import { describe, it, expect } from 'vitest';
import { buildDigest, digestSession, promptEntries, promptsSince, HEURISTIC_LABEL_RE, MAX_PROMPTS, type DigestInput } from '../../../src/core/conversations/digest.js';
import type { TranscriptEntry } from '../../../src/core/agents/claude/transcript-entry.js';
import { claudeEntries } from '../../../src/core/agents/claude/entries.js';

const T0 = Date.parse('2026-09-29T08:00:00Z');
const at = (min: number) => new Date(T0 + min * 60_000).toISOString();
const you = (min: number, content: unknown, extra: Partial<TranscriptEntry> = {}): TranscriptEntry =>
  ({ type: 'user', timestamp: at(min), message: { content }, ...extra });

describe('promptsSince', () => {
  it('keeps what you typed in the window, oldest first, and nothing Claude Code wrote for you', () => {
    const t: TranscriptEntry[] = [
      you(-30, 'yesterday: set up the repo'),
      you(5, 'Add the CSV export', { uuid: 'u5' }),
      { type: 'assistant', timestamp: at(6), message: { content: 'On it' } },
      you(7, [{ type: 'tool_result', tool_use_id: 'x', content: 'ok' }]), // Claude's own loop
      you(8, '<command-name>/clear</command-name>'),
      you(9, 'Caveat: The messages below were generated by the user while running local commands.'),
      you(10, 'meta', { isMeta: true }),
      you(11, 'subagent prompt', { isSidechain: true }),
      you(12, [{ type: 'text', text: 'Also   quote\ncommas' }]),
      you(13, '<task-notification>\n<task-id>abc</task-id>\n<status>completed</status>\n</task-notification>'),
      you(14, '[Request interrupted by user for tool use]'),
      you(5, 'Add the CSV export', { uuid: 'u5' }), // the same entry, seen again (another tail read)
    ];
    expect(promptsSince([claudeEntries(t)], T0)).toEqual([
      { ts: at(5), text: 'Add the CSV export' },
      { ts: at(12), text: 'Also quote commas' },
    ]);
  });

  it('typing the same thing three times is three prompts', () => {
    const t = [you(1, 'commit', { uuid: 'a' }), you(2, 'run the tests', { uuid: 'b' }), you(3, 'commit', { uuid: 'c' }), you(4, 'commit')];
    expect(promptsSince([claudeEntries(t)], T0).map((p) => p.text)).toEqual(['commit', 'run the tests', 'commit', 'commit']);
  });

  it('merges several conversations by time and clips long prompts', () => {
    const a = [you(20, 'second')];
    const b = [you(10, 'first'), you(30, 'x'.repeat(500))];
    const p = promptsSince([claudeEntries(a), claudeEntries(b)], T0);
    expect(p.map((x) => x.text.slice(0, 6))).toEqual(['first', 'second', 'xxxxxx']);
    expect(p[2].text).toHaveLength(240);
  });
});

const input = (over: Partial<DigestInput> = {}): DigestInput => ({
  sessionId: 's1', target: 'api', branch: 'feat/x', isGroup: false,
  lastAccessedAt: at(0), archivedAt: null, status: null, transcripts: [], checkpoints: [], diffStat: null, ci: null,
  ...over,
});

describe('digestSession', () => {
  it('counts the turns finished in the window, with the names already made', () => {
    const d = digestSession(
      input({
        checkpoints: [
          { id: 0, ts: at(1), label: 'Initial' },
          { id: 1, ts: at(-60), label: 'yesterday' },
          { id: 2, ts: at(20), label: 'Wrote the export' },
          { id: 3, ts: at(40) },
        ],
        status: { state: 'idle', summary: 'Done: export + tests', updatedAt: at(41) },
      }),
      T0,
    )!;
    expect(d.turns).toBe(2);
    expect(d.turnLabels).toEqual(['Wrote the export']);
    expect(d).toMatchObject({ state: 'idle', summary: 'Done: export + tests', lastActivity: at(41) });
  });

  it('is left out when nothing happened in the window', () => {
    expect(digestSession(input({ transcripts: [claudeEntries([you(-5, 'old')])], checkpoints: [{ id: 1, ts: at(-5) }] }), T0)).toBeNull();
  });

  it('leaves out the size-only names a turn gets when Claude was unavailable', () => {
    for (const l of ['3 files · +52 −8', '1 file · +1 −0', 'no changes']) expect(HEURISTIC_LABEL_RE.test(l)).toBe(true);
    expect(HEURISTIC_LABEL_RE.test('Renamed 3 files')).toBe(false);
    const d = digestSession(
      input({ checkpoints: [{ id: 1, ts: at(5), label: '3 files · +52 −8' }, { id: 2, ts: at(6), label: 'Wrote the export' }, { id: 3, ts: at(7), label: 'no changes' }] }),
      T0,
    )!;
    expect(d.turns).toBe(3);
    expect(d.turnLabels).toEqual(['Wrote the export']);
  });

  it('says when a transcript was too large to read back to the window', () => {
    expect(digestSession(input({ transcripts: [claudeEntries([you(1, 'x')])], transcriptsPartial: true }), T0)?.partial).toBe(true);
    expect(digestSession(input({ transcripts: [claudeEntries([you(1, 'x')])] }), T0)?.partial).toBeUndefined();
  });

  it('a PR merged in the window counts, even without prompts; lists every PR', () => {
    const ci = {
      checkedAt: at(50),
      repos: [
        { name: 'api', done: true, pr: { number: 7, url: 'u7', state: 'MERGED' as const, mergedAt: at(45), isDraft: false, mergeStateStatus: 'CLEAN', checks: 'pass' as const, headSha: 'a' } },
        { name: 'web', done: false, pr: null },
      ],
    };
    const d = digestSession(input({ ci }), T0)!;
    expect(d.prs).toEqual([{ repo: 'api', number: 7, url: 'u7', state: 'MERGED', mergedAt: at(45) }]);
    expect(d.lastActivity).toBe(at(45)); // the merge is its activity, so it sorts by it
  });

  it(`keeps the last ${MAX_PROMPTS} prompts and says how many came before`, () => {
    const t = Array.from({ length: MAX_PROMPTS + 3 }, (_, i) => you(i + 1, `prompt ${i}`));
    const d = digestSession(input({ transcripts: [claudeEntries(t)] }), T0)!;
    expect(d.prompts).toHaveLength(MAX_PROMPTS);
    expect(d.prompts[0].text).toBe('prompt 3');
    expect(d.morePrompts).toBe(3);
  });
});

describe('buildDigest', () => {
  it('only sessions that did something, most recent first', () => {
    const rows = buildDigest(
      [
        input({ sessionId: 'early', transcripts: [claudeEntries([you(5, 'a')])] }),
        input({ sessionId: 'quiet' }),
        input({ sessionId: 'late', transcripts: [claudeEntries([you(50, 'b')])] }),
        input({ sessionId: 'archived', archivedAt: at(30) }),
      ],
      T0,
    );
    expect(rows.map((r) => r.sessionId)).toEqual(['late', 'archived', 'early']);
  });
});

describe('promptEntries', () => {
  it('keeps only your prompts (uuid, time, text), and the digest reads the same from them', () => {
    const big = 'x'.repeat(100_000);
    const entries = [
      { type: 'user', uuid: 'u1', timestamp: '2026-09-30T09:00:00Z', message: { role: 'user', content: 'Fix the login redirect' } },
      { type: 'assistant', timestamp: '2026-09-30T09:00:01Z', message: { content: [{ type: 'text', text: big }] } },
      { type: 'user', timestamp: '2026-09-30T09:00:02Z', message: { content: [{ type: 'tool_result', content: big }] } },
      { type: 'user', uuid: 'u2', timestamp: '2026-09-30T10:00:00Z', message: { role: 'user', content: [{ type: 'text', text: 'Now add a test' }] } },
    ] as unknown as TranscriptEntry[];
    const slim = promptEntries(claudeEntries(entries));
    expect(slim).toHaveLength(2);
    expect(JSON.stringify(slim).length).toBeLessThan(400); // not the 200 KB of tool output
    const since = Date.parse('2026-09-30T00:00:00Z');
    expect(promptsSince([slim], since)).toEqual(promptsSince([claudeEntries(entries)], since));
    expect(promptsSince([slim, slim], since)).toHaveLength(2); // still deduped by uuid
  });
});
